#首先指定服务注册中心的地址为http://localhost:8761/eureka/，
#服务的端口为8769，服务名为service-zuul；
#以/api-ribbon/ 开头的请求都转发给service-ribbon服务；
#以/api-feign/开头的请求都转发给service-feign服务；
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: ribbon-service-consume
    api-b:
      path: /api-feign/**
      serviceId: feign-service-comsume